// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {obfuscator} from '../models';
import {context} from '../models';

export function Config():Promise<obfuscator.Config>;

export function Obfuscate(arg1:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
