// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Config() {
  return window['go']['obfuscator']['obfuscator']['Config']();
}

export function Obfuscate(arg1) {
  return window['go']['obfuscator']['obfuscator']['Obfuscate'](arg1);
}

export function SetContext(arg1) {
  return window['go']['obfuscator']['obfuscator']['SetContext'](arg1);
}
