// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function MessageInfoDialog(arg1:string,arg2:string):Promise<void>;

export function OpenDirectoryDialog():Promise<Array<string>>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function OpenMultipleFilesDialog():Promise<Array<string>>;

export function SetContext(arg1:context.Context):Promise<void>;
