// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MessageInfoDialog(arg1, arg2) {
  return window['go']['filesystem']['Dialog']['MessageInfoDialog'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['filesystem']['Dialog']['OpenDirectoryDialog']();
}

export function OpenFileLocation(arg1) {
  return window['go']['filesystem']['Dialog']['OpenFileLocation'](arg1);
}

export function OpenMultipleFilesDialog() {
  return window['go']['filesystem']['Dialog']['OpenMultipleFilesDialog']();
}

export function SetContext(arg1) {
  return window['go']['filesystem']['Dialog']['SetContext'](arg1);
}
