// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadFile(arg1) {
  return window['go']['filesystem']['FileManager']['ReadFile'](arg1);
}

export function SetContext(arg1) {
  return window['go']['filesystem']['FileManager']['SetContext'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['filesystem']['FileManager']['WriteFile'](arg1, arg2);
}
