// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportEncryptedFiles(arg1) {
  return window['go']['main']['App']['ExportEncryptedFiles'](arg1);
}

export function ObfuscateJS(arg1, arg2) {
  return window['go']['main']['App']['ObfuscateJS'](arg1, arg2);
}

export function OpenFiles() {
  return window['go']['main']['App']['OpenFiles']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenImportedFileLocation(arg1) {
  return window['go']['main']['App']['OpenImportedFileLocation'](arg1);
}

export function ReadFilesContent(arg1) {
  return window['go']['main']['App']['ReadFilesContent'](arg1);
}
