// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ObfuscateJS(arg1:string):Promise<string>;

export function OpenFiles():Promise<Array<string>>;

export function ReadFilesContent(arg1:Array<string>):Promise<{[key: string]: string}>;
