// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportEncryptedFiles(arg1:{[key: string]: string}):Promise<void>;

export function ObfuscateJS(arg1:string,arg2:main.ObfuscationConfig):Promise<string>;

export function OpenFiles():Promise<Array<string>>;

export function OpenFolder():Promise<Array<string>>;

export function OpenImportedFileLocation(arg1:string):Promise<void>;

export function ReadFilesContent(arg1:Array<string>):Promise<{[key: string]: string}>;
